#!/usr/bin/env python3
"""
Generate a derived TPC-DS DDL with configurable stringification levels.

This script reads the canonical TPC-DS schema (unmodified, with license header),
applies type overrides for selected columns, and writes a derived DDL that
preserves the original layout/comments.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Mapping, MutableMapping, Sequence, Set

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from workload import stringification

DEFAULT_BASE_SCHEMA = REPO_ROOT / "tpcds-kit" / "tools" / "tpcds.sql"
GENERATED_COMMENT_TMPL = (
    '-- Generated by tools/generate_tpcds_schema.py with stringification level {level}'
    "{preset}\n"
)

CREATE_TABLE_RE = re.compile(r"\s*create\s+table\s+([A-Za-z0-9_]+)", re.IGNORECASE)
COLUMN_DEF_RE = re.compile(r"(\s*)([A-Za-z0-9_]+)(\s+)([^,\s]+)(.*)")
NUMERIC_PREFIXES = ("int", "integer", "bigint", "smallint", "decimal", "number", "numeric")


def _positive_int(raw: str) -> int:
    try:
        value = int(raw)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid int value: {raw}") from exc
    if value < 1:
        raise argparse.ArgumentTypeError("value must be >= 1")
    return value


def _is_numeric_type(token: str) -> bool:
    lowered = token.strip().lower()
    return lowered.startswith(NUMERIC_PREFIXES)


def _rewrite_line(
    line: str,
    table: str | None,
    targets: Mapping[str, Mapping[str, str]],
    rewritten_columns: Set[str],
) -> str:
    if not table or table not in targets:
        return line

    match = COLUMN_DEF_RE.match(line)
    if not match:
        return line

    _, col_name, spacing, data_type, rest = match.groups()
    col_key = f"{table}.{col_name.lower()}"
    if col_key not in targets[table]:
        return line
    target_type = targets[table][col_key]
    if not _is_numeric_type(data_type):
        return line

    rewritten_columns.add(col_key)
    return f"{match.group(1)}{col_name}{spacing}{target_type}{rest}"


def _insert_generated_comment(lines: List[str], level: int, preset: str | None) -> List[str]:
    preset_label = f' (preset \"{preset}\")' if preset else ""
    comment_line = GENERATED_COMMENT_TMPL.format(level=level, preset=preset_label)
    if comment_line in lines:
        return lines

    insert_pos = 0
    for idx, line in enumerate(lines):
        if line.lstrip().startswith("--"):
            insert_pos = idx + 1
            continue
        break

    return lines[:insert_pos] + [comment_line] + lines[insert_pos:]


def rewrite_schema(
    base_lines: List[str],
    rewrite_columns: Mapping[str, str],
) -> List[str]:
    targets: MutableMapping[str, Dict[str, str]] = defaultdict(dict)
    for col, target_type in rewrite_columns.items():
        table, _, column = col.partition(".")
        if not table or not column:
            continue
        targets[table.lower()][f"{table.lower()}.{column.lower()}"] = target_type

    output: List[str] = []
    current_table: str | None = None
    rewritten_columns: Set[str] = set()

    for line in base_lines:
        create_match = CREATE_TABLE_RE.match(line)
        if create_match:
            current_table = create_match.group(1).lower()

        if current_table and line.lstrip().startswith(")"):
            current_table = None

        new_line = _rewrite_line(line, current_table, targets, rewritten_columns)
        output.append(new_line)

    missing = set(rewrite_columns) - rewritten_columns
    if missing:
        missing_display = ", ".join(sorted(missing))
        raise ValueError(f"Failed to rewrite expected columns: {missing_display}")

    return output


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate derived TPC-DS DDL using stringification levels.")
    parser.add_argument(
        "--stringification-level",
        "--level",
        dest="stringification_level",
        type=_positive_int,
        help="Stringification level (1-15; default: 10).",
    )
    parser.add_argument(
        "--stringification-preset",
        "--preset",
        dest="stringification_preset",
        type=str,
        choices=sorted(stringification.PRESET_LEVELS.keys()),
        help="Stringification preset name.",
    )
    parser.add_argument("--base-schema", type=Path, default=DEFAULT_BASE_SCHEMA, help="Path to the canonical TPC-DS DDL.")
    parser.add_argument(
        "--baseline-schema",
        type=Path,
        default=stringification.DEFAULT_PROD_SCHEMA,
        help="Schema used to derive production-aligned recast columns.",
    )
    parser.add_argument(
        "--str-plus-max-level",
        type=_positive_int,
        default=stringification.DEFAULT_STR_PLUS_MAX_LEVEL,
        help="Maximum accepted STR level in STR+ mode (default: 20).",
    )
    parser.add_argument(
        "--str-plus-pad-step",
        type=_positive_int,
        default=2,
        help="Extra suffix growth per level above STR10 (default: 2).",
    )
    parser.add_argument(
        "--str-plus-separator",
        type=str,
        default="~",
        help="Suffix separator for STR+ amplification (default: ~).",
    )
    parser.add_argument(
        "--str-plus-marker",
        type=str,
        default="X",
        help="Suffix marker for STR+ amplification (default: X).",
    )
    parser.add_argument("--out", type=Path, required=True, help="Output path for the derived DDL.")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    if args.stringification_level is not None and args.stringification_preset is not None:
        raise SystemExit("--stringification-level and --stringification-preset are mutually exclusive.")
    resolved_level, resolved_preset = stringification.resolve_level(
        args.stringification_level,
        args.stringification_preset,
        allow_extended=True,
        max_level=int(args.str_plus_max_level),
    )
    config = stringification.build_stringification_config(
        level=resolved_level,
        preset=resolved_preset,
        base_schema_path=args.base_schema,
        prod_schema_path=args.baseline_schema,
        str_plus_max_level=int(args.str_plus_max_level),
        str_plus_pad_step=int(args.str_plus_pad_step),
        str_plus_separator=str(args.str_plus_separator),
        str_plus_marker=str(args.str_plus_marker),
    )

    if not args.base_schema.exists():
        raise FileNotFoundError(f"Base schema not found at {args.base_schema}")

    base_lines = args.base_schema.read_text(encoding="utf-8").splitlines(keepends=True)
    rewrite_map = {col: config.schema_type_map[col] for col in config.schema_selected}
    output_lines = rewrite_schema(base_lines, rewrite_map) if rewrite_map else list(base_lines)
    output_lines = _insert_generated_comment(output_lines, config.level, config.preset)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(output_lines), encoding="utf-8")
    manifest_path = args.out.parent / stringification.SCHEMA_MANIFEST_NAME
    stringification.write_json(
        manifest_path,
        {
            "stringification_level": config.level,
            "stringification_preset": config.preset,
            "intensity": config.intensity,
            "k_schema": config.k_schema,
            "K_schema_max": config.K_schema_max,
            "recast_columns": list(config.schema_selected),
            "recast_type_map": {col: config.schema_type_map[col] for col in config.schema_selected},
            "base_schema": str(args.base_schema),
            "baseline_schema": str(args.baseline_schema),
            "str_plus_enabled": bool(config.str_plus_enabled),
            "amplification": {
                "enabled": bool(config.str_plus_enabled),
                "extra_pad": int(config.amplification_extra_pad),
                "pad_step": int(config.amplification_pad_step),
                "separator": str(config.amplification_separator),
                "marker": str(config.amplification_marker),
            },
        },
    )
    print(f"Wrote derived schema to {args.out} with stringification level {config.level}.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # pragma: no cover - CLI guardrail
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)
